static app without grow view and texts
h3770k1k1/cureapp pull request #6
Opened 2024-09-09 18:37 UTC by h3770k1k1

not actually right name its definitely not static

2024-12-07 11:06 UTC, kamil-ciesla requested changes
ogólna ocena: dobrze, ale problemy na poziomie architekturalnym oraz brak kilku dobrych praktyk.

Dwie główne myśli:
Tworzenie komponentów które są reużywalne, to kluczowa praktyka w programowaniu. Im więcej tak robisz, tym bardziej zyskujesz. W przeciwnym razie strzelasz sobie w stopę. 

Każdy język/framework ma swoją filozofię, za którą domyślnie warto podążać. React np. wykorzystuje koncept Single Source of Truth, w ten sposób, że dane są przekazywane jedynie z góry na dół (Waterfall), dlatego też wiele razy wspominam o przekazywaniu danych za pomocą propsów.

Jeśli nie kojarzysz dobrze dobrych praktyk (nie tylko odnośnie reacta), to warto o nich poczytać, zazwyczaj ujęte są w formie różnych skrótów typu SOLID albo DRY.

2024-12-07 11:06 UTC, kamil-ciesla commented on src/App.jsx
> +import Article6 from "./Views/Articles/Cialo/BodyArticle6";
Dlaczego bodyarticle to article? a reszta article posiada swoje prefixy?

2024-12-07 11:06 UTC, kamil-ciesla commented on src/App.jsx
> +import MindArticle4 from "./Views/Articles/Umysl/MindArticle4";
Skoro zaczęłaś używać numeracji, to znak, że trzeba to zrefactorować, klasy/komponenty nie powinny mieć numeracji.

Powinien być jeden Article component, z którego dziedziczą BodyArticle, MindArticle etc. Ewentualnie może też nie być Article, jeśli aż tak mało są ze sobą powiązane te komponenty, tylko czy wtedy dalej powinny się nazywać Article?

Z tego co opowiadałaś o Figmie, jak różne są to artykuły, rozumiem troche dlaczego zdecydowałaś się na taki rozdział. Mimo tego, to nie jest dobra praktyka. Po to są komponenty, żeby były reużywalne, taka numeracja na to nie pozwala (skąd masz wiedzieć który article to ten właściwy?). React został tak stworzony, żeby komponenty dało się używać ponownie, wypełniać różnymi danymi, i się do nich dostosować. Jeśli design wizualny aplikacji wymusza całkowitą indywidualność stron, to albo trzeba dostosować do tego kod, żeby Article się dopasowywał, albo po prostu robić statyczne widoki.

Jeśli jednak uważasz że te artykuły są aż tak różne, i nie ma sensu tworzyć jednego wspólnego komponentu, to proponuje nazwać je chociaż troche inaczej, jeśli i tak mają być zahardkodowane

2024-12-07 11:06 UTC, kamil-ciesla commented on src/App.jsx
> +                                />
wygląda jakby przydało się zastosować prettier

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/AreaSubpage.jsx
> +  const text = index !== -1 ? MentalTexts[index] : null;
czemu chcesz żeby text był nullem? troche ryzyko, że sypnie błędem, może lepiej użyć pustego stringa?  (tylko pamiętaj, że wtedy może być inaczej wyewaluowany w ifie)

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/AreaSubpage.jsx
> +  const index = MentalTexts.findIndex((item) => item.Color === activeColor);
dane do komponentu powinny być przekazywane przez parent komponent jako propsy. Jeśli ładujesz je bezpośrednio z tego komponentu to omijasz zasady/zalety reacta.

Raczej lepiej jest załadować sobie wszystko level wyżej i następnie rozprowadzić po child komponentach. W ten sposób odciążasz child komponenty z logiki ładowania

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/ArticleHeader.jsx
> +const ArticleHeader = ({ dotCount, filledDotIndex }) => {
o ile dobrze rozumiem dotCount, to jest to licznik 'kropek' służących do przesuwania, myślę, że można zastosować bardziej deskryptywną nazwę typu pageCount. jeśli się zgadzasz to zmień

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/ArticleHeader.jsx
> +   };
to bardzo duże mapowanie, zastanawiam się do czego służy, czy musi być całe w jednej zmiennej, oraz dlaczego posiada również informacje o kolorach.

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/ArticleHeader.jsx
> +     MindArticle1: { target: "Mental", params: { activeColor: "#FFE2CC", activeArea: "UMYSŁ" } },
kolorki do constantów pamiętaj ;)

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/BottomMenu.jsx
> +};
czy Views powinno być zdefiniowane w BottomMenu?

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/BottomMenu.jsx
> +        onPress={() => navigation.navigate(Views.Home)}
plusik za czytelność

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/Carousel.jsx
> +});
wcześniej style wrzucałaś przed komponentem, a tutaj w komponencie

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/ExitView.jsx
> +        <Option text="monitoruj swój rozwój" index={5} />
powinno być at least w stałych (objekt key,value a la json) albo w pliku.

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/LetterDropDown.jsx
> +  linkText2,
uważaj na numerki, mało mówią

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/MenuOption.jsx
> +];
zmienna good, ale brakuje nazw. Jeśli dostałabyś taki kod, to wiedziałabyś jakiego koloru użyć bez googlowania?

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/Navbar.jsx
> +
czy te komentarze są potrzebne? jeśli tak, to englishify.

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/Navbar.jsx
> +                {["c", "u", "r", "e", "d"][index]}
czy nie powinno to być w zmiennej?

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Components/SmallSection.jsx
> +  };
co tu się w ogóle dzieje? :d zastanów się jak to można zrefactorować, na pewno wiesz jak jak

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Views/Articles/Cialo/BodyArticle1.jsx
> +const Article1 = ({ navigation }) => {
jeszcze jednym zasadniczym problemem tworzenia komponentów z numeracją jest to, że po prostu piszesz bardzo dużo podobnego kodu, why work more?

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Views/Articles/Cialo/BodyArticle6.jsx
> +  const article = bodyArticleTexts[5];
zdecydowanie przekazywanie tekstów powinno tutaj być przez propsy

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Views/Articles/Cialo/BodyArticleText.jsx
> +      "Bądź dla/na siebie uważn_ i czuł_. Zapisuj swoje odczucia z ciała oraz spróbuj zrozumieć, co przez nie próbuje powiedzieć Ci Twój organizm – oraz postaraj się na nie odpowiadać. Spójrz na poni
ten plik to jeden ze sposobów na to żeby odseparować dane, treść. Czy dobry? Trudno mi powiedzieć. To jest ogólnie duży problem w developowaniu programów/systemów, jak przechować dane w dobry sposób.

Mogę powiedzieć jedynie tyle na przyszłość, że warto to dobrze przemyśleć, zanim się zdecyduje na konkretny approach, bo potem trudno może być go zmienić, albo może być to praktycznie niemożliwe ze względu na czasochłonność

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Views/Articles/Cialo/BodyArticleText.jsx
> +    MediumText: "https://open.spotify.com/episode/38EitNF4WKsNBbMCkiSd2X",
link do spotify w środku treści? sounds like something that will break eventually.

Also linki powinny być w hrefach

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Views/Articles/Dusza/SoulArticle3.jsx
> +  };
takie mapowanie, gdzie w nazwie komponentu masz jeden numer, a potem w jego środku masz kolejny numer, ale w stringu, to po pierwsze zła praktyka, po drugie może się bardzo szybko zemścić, jeśli tylko będziesz zmieniać ten flow.

2024-12-07 11:06 UTC, kamil-ciesla commented on src/Views/Articles/Dusza/SoulArticle6.jsx
> +  };
jak w poprzednim komentarzu, co jeśli chciałabyś dodać kolejny artykuł?

2024-12-07 11:13 UTC, h3770k1k1 commented on src/App.jsx
> +                                />
to prettier xrobił :D

2024-12-07 11:14 UTC, h3770k1k1 commented on src/App.jsx
> +import Article6 from "./Views/Articles/Cialo/BodyArticle6";
zagapionko

2024-12-09 18:16 UTC, h3770k1k1 commented on src/App.jsx
> +import Article6 from "./Views/Articles/Cialo/BodyArticle6";
Fixed

2024-12-10 19:45 UTC, h3770k1k1 commented on src/Components/ArticleHeader.jsx
> +const ArticleHeader = ({ dotCount, filledDotIndex }) => {
done

2024-12-10 19:46 UTC, h3770k1k1 commented on src/Components/Carousel.jsx
> +});
fixed

2024-12-10 19:47 UTC, h3770k1k1 commented on src/Components/LetterDropDown.jsx
> +  linkText2,
uważam ze tutaj to jest okej bo to dosłownie jest to

2024-12-10 19:50 UTC, h3770k1k1 commented on src/Components/Navbar.jsx
> +
usunięte

2024-12-10 19:53 UTC, h3770k1k1 commented on src/Components/AreaSubpage.jsx
> +  const text = index !== -1 ? MentalTexts[index] : null;
done

2024-12-10 22:22 UTC, h3770k1k1 commented on src/Views/Articles/Dusza/SoulArticle6.jsx
> +  };
fixd

2024-12-11 22:25 UTC, h3770k1k1 commented on src/Components/MenuOption.jsx
> +];
to wtedy nic nie robiło nawet tylko sobie leżało i czekało aż rusze, fixed

2024-12-14 12:48 UTC, h3770k1k1 commented on src/Components/ArticleHeader.jsx
> +   };
fixed

2024-12-22 20:57 UTC, h3770k1k1 commented on src/Components/SmallSection.jsx
> +  };
fixed

2024-12-23 20:54 UTC, h3770k1k1 commented on src/App.jsx
> +                                />
niema juz tego fixed

2024-12-23 20:56 UTC, h3770k1k1 commented on src/Components/BottomMenu.jsx
> +        onPress={() => navigation.navigate(Views.Home)}
(y)

2024-12-23 20:57 UTC, h3770k1k1 commented on src/Components/ArticleHeader.jsx
> +     MindArticle1: { target: "Mental", params: { activeColor: "#FFE2CC", activeArea: "UMYSŁ" } },
fixed

2024-12-24 06:51 UTC, h3770k1k1 commented on src/Components/BottomMenu.jsx
> +};
poprawione

2024-12-25 21:37 UTC, h3770k1k1 commented on src/Components/Navbar.jsx
> +                {["c", "u", "r", "e", "d"][index]}
fixed

2024-12-26 08:25 UTC, h3770k1k1 commented on src/Components/MenuOption.jsx
> +];
teraz fixed

2024-12-27 13:37 UTC, h3770k1k1 commented on src/Components/ExitView.jsx
> +        <Option text="monitoruj swój rozwój" index={5} />
fixed

2025-01-26 10:19 UTC, merged